### ISSUE TITLE
Emoji not replaced in Gboard and others

### ISSUE THREAD

**Issue by pmdevita** [Magisk-Modules-Repo/blobmoji#2]
This affects my Samsung Tab S3 running 7.0 and my HTC 10 running 8.0 although in slightly different ways.

On my Tab S3, the blobs only seem to appear in Firefox. Gboard, Chrome, and Magisk Manager show the Samsung emoji.

On my HTC 10, only the Noto emoji that HTC normally falls back to is replaced. Textra showed the blobs but I didn't test anything else.

I know for certain that the previous notoemoji replacer that I think was also made by you didn't have this issue on the Tab S3 and I think it was the same for the HTC 10.

My guess, knowing very little about how fonts work on Android, is that unlike notoemoji replacer, which replaced the system's default emoji, this one only replaces the fallback font.

Anything else I can add? Thanks!

**Comment by simonsmh** [comment]
Let me track this issue. Please post up your /system/etc/fonts.xml, thanks.
Emoji not replaced in Gboard may cause by upstream ttx missing but I'm not sure.

**Comment by pmdevita** [comment]
Here they are.
[Tab S3 fonts.xml.txt](https://github.com/Magisk-Modules-Repo/magisk-blobmoji/files/1771842/Tab.S3.fonts.xml.txt)
[HTC 10 fonts.xml.txt](https://github.com/Magisk-Modules-Repo/magisk-blobmoji/files/1771843/HTC.10.fonts.xml.txt)

**Comment by simonsmh** [comment]
Notoemoji replacer tries to modify the fonts.xml which leads to  comparability issues. I will try to fix this issue in another way later but it will take time. Thanks for your report.

**Comment by pmdevita** [comment]
No problem, thanks for the module.

**Comment by simonsmh** [comment]
Please try latest version.

**Comment by pmdevita** [comment]
It didn't seem to make a difference on either device.

**Comment by simonsmh** [comment]
please post related logs here, including magisk logs.

**Comment by simonsmh** [comment]
Please try the latest test version. @pmdevita

**Comment by pmdevita** [comment]
Sorry for getting this to you so late. Here they are using the newest version. This version appears to fix the problem as the blob emoji now show up in all apps
[Tab S3.log](https://github.com/Magisk-Modules-Repo/magisk-blobmoji/files/1835362/Tab.S3.log)
[HTC 10.log](https://github.com/Magisk-Modules-Repo/magisk-blobmoji/files/1835363/HTC.10.log)

Did you want the logcat from boot as well? The Magisk log seems to include the relevant messages already.

**Comment by simonsmh** [comment]
The problem is fixed.
If there is any other problem, please report it to me. Thanks.
