### ISSUE TITLE
Emoji not showing after installing module

### ISSUE THREAD

**Issue by someone755** [Magisk-Modules-Repo/blobmoji#4]
After installing and rebooting the system emoji are replaced with crossed out rectangles. Running stock Marshmallow 6.0.1 with Magisk 17.1 on Sony Xperia Z3 Compact. This causes keyboard to crash when opening emoji panel: https://i.imgur.com/kA4udpX.png
Have tried removing and reinstalling module but issue persists. Have tried searching for a solution online but cannot find one, any help is appreciated

**Comment by simonsmh** [comment]
Cannot reproduce on my side. Any logs?
