### ISSUE TITLE
Not working on Samsung devices

### ISSUE THREAD

**Issue by kgptzac** [Magisk-Modules-Repo/blobmoji#6]
Been upgraded to Pie for a couple of days and I noticed default emojis are shown instead of blobs.

**Comment by simonsmh** [comment]
Cannot reproduce. What device are you using?

**Comment by kgptzac** [comment]
I'm using galaxy note 9, Android Pie, magisk v18.0

**Comment by simonsmh** [comment]
What's the emoji file name in your /system/fonts?

**Comment by kgptzac** [comment]
I'm not sure which one of the 309 files in the fonts folder is that said file. I'm also using a font that's not the default font (using Samsung Sans now).

**Comment by simonsmh** [comment]
The basic logic is that it replaces the font file of the system, as the most of the oem systems use the same font Noto Color Emoji, it will just make a replacement. But for Samsung they are using their dedicated emoji file. If you can find the emoji file name, you can replace it as well.

**Comment by kgptzac** [comment]
Two files contain 'emoji':

NotoColorEmoji.ttf
SamsungColorEmoji.tff

So the module has to replace both of these files?

**Comment by simonsmh** [comment]
Can you provide a copy of /system/etc/fonts.xml?

**Comment by kgptzac** [comment]
I have uploaded here
https://drive.google.com/file/d/1inhBZ31W87mKjLh3igFV-ryXxCv6S5VA/view?usp=drivesdk
